server:
  port: 8081

spring:
  application:
    name: patient
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/patient
    username: root
    jpa:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          format_sql: true
      show-sql: true

  mvc:
    format:
      date: yyyy-MM-dd

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true